server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crimeservice
    username: postgres
    password: admin
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: INFO
  cloud:
    config:
      enabled: false
  application:
    name: crime-service
  config:
    import:
     config-server: http://localhost:8083

external-api:
  uri: "http://localhost:8080/places/police-stations?latitude={latitude}&longitude={longitude}"

