apiVersion: apps/v1
kind: Deployment
metadata:
  name: crime-service
  namespace: default
  labels:
    app: crime-service
spec:
  selector:
    matchLabels:
      app: crime-service  # Consistent label
  replicas: 2  # High availability
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crime-service  # Consistent label
    spec:
      containers:
      - name: crime-service
        image: geecpu/crimeservice:latest  # Specify image tag
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
       
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_server_url
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-cm  # Correct ConfigMap reference
                key: hostname
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: crime-service-svc
  namespace: default
spec:
  selector:
    app: crime-service  # Consistent label
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: crime-service-port
    protocol: TCP
    port: 80
    targetPort: 8082
